### ISSUE TITLE
failed to load storage driver, err:StorageDriver not registered: gcs

### ISSUE THREAD

**Issue by sharkymcdongles** [bitnami/bitnami-docker-harbor-registryctl#2]
Seems related to this:

https://github.com/caervs/distribution/commit/f163759f18cee0c2dda72b2a625115038a5ecd83

https://github.com/docker/distribution/issues/2819

I am using this version: 2.1.0-debian-10-r29

**Comment by juan131** [comment]
Hi @sharkymcdongles 

```bash
$ docker run --rm -it bitnami/harbor-registry /opt/bitnami/harbor-registry/bin/registry --version
...
/opt/bitnami/harbor-registry/bin/registry github.com/docker/distribution v2.7.1
```

We're including the docker distribution **2.7.1** on this image and the binary is compiled using [blacksmith](https://github.com/bitnami/blacksmith) with a recipe that includes the piece of code below:


```
    this.sandbox.runProgram(
      'git',
      ['clone', '-b', `v${this.version}`, 'http://github.com/docker/distribution', this.srcDir]
    );
    this.sandbox.runProgram(
      'make',
      ['clean', 'binaries'],
      {
        cwd: this.srcDir,
        env: {
          PATH: `${process.env.PATH}:${this.goPath}/bin:${process.env.HOME}/go/bin:/usr/local/go-${this.goVersion}/bin`,
          GOPATH: this.goPath,
          CGO_ENABLED: 0,
          BUILDTAGS: 'include_oss include_gcs',
        },
      }
    );
```

As you can see, it's setting the environment variable `BUILDTAGS` properly.

**Comment by sharkymcdongles** [comment]
Then there's another problem. It works flawlessly with the stock chart.

Have you tried testing it with GCS enabled?

**Comment by juan131** [comment]
Hi @sharkymcdongles 

What chart do you refer to? Could you please share a link to the chart and image used on that chart so I can give it a try? Thanks in advance.

**Comment by sharkymcdongles** [comment]
@juan131 

https://charts.bitnami.com/bitnami

Harbor version 7.4.3

Relevant values to enable GCS:
```
imageChartStorage:
        ## Name of a secret contaning the CA bundle
        ##
        caBundleSecretName:
        ## Specify whether to disable `redirect` for images and chart storage, for
        ## backends which not supported it (such as using minio for `s3` storage type), please disable
        ## it. To disable redirects, simply set `disableredirect` to `true` instead.
        ## ref: https://github.com/docker/distribution/blob/master/docs/configuration.md#redirect
        ##
        disableredirect: false
        ## Specify the type of storage. Allowed values are [ filesystem | azure | gcs | s3 | swift | oss ]
        ##
        type: gcs
        gcs:
          bucket: harbor
          ## The base64 encoded json file which contains the gcs key (file's content)
          ##
          encodedkey: censored
          rootdirectory: /
          chunksize: "5242880"
    logLevel: debug
```
